# Ansible inventory created from ['/workspaces/nornir-config/netlab/topology.yml', '/workspaces/nornir-config/netlab/defaults.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
ansible_user: admin
ansible_ssh_pass: admin
ansible_network_os: eos
ansible_connection: network_cli
ansible_become: 'yes'
ansible_become_method: enable
