# Ansible inventory created from ['/workspaces/nornir-config/netlab/topology.yml', '/workspaces/nornir-config/netlab/defaults.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
all: {}
modules:
  hosts:
    edge1: {}
    edge2: {}
    core1: {}
custom_configs:
  hosts:
    edge1: {}
    edge2: {}
    core1: {}
daemons:
  hosts: {}
eos:
  hosts:
    edge1:
      ansible_host: clab-netlab-edge1
      id: 1
    edge2:
      ansible_host: clab-netlab-edge2
      id: 2
    core1:
      ansible_host: clab-netlab-core1
      id: 3
linux:
  hosts:
    h1:
      ansible_host: clab-netlab-h1
      id: 4
    h2:
      ansible_host: clab-netlab-h2
      id: 5
    h3:
      ansible_host: clab-netlab-h3
      id: 6
    h4:
      ansible_host: clab-netlab-h4
      id: 7
edge:
  hosts:
    edge1: {}
    edge2: {}
core:
  hosts:
    core1: {}
host:
  hosts:
    h1: {}
    h2: {}
    h3: {}
    h4: {}
as65001:
  hosts:
    edge1: {}
    edge2: {}
