# Ansible inventory created from ['/workspaces/nornir-config/netlab/topology.yml', '/workspaces/nornir-config/netlab/defaults.yml', 'package:topology-defaults.yml']
#

%YAML 1.1
---
interfaces:
- ipv4: 172.16.0.4/24
  type: lan
  role: stub
  bridge: netlab_3
  linkindex: 3
  name: h1 -> edge1
  ifindex: 1
  ifname: eth1
  mtu: 1500
  neighbors:
  - ifname: Ethernet2
    node: edge1
    vrf: CustA
    ipv4: 172.16.0.1/24
  gateway:
    ipv4: 172.16.0.1/24
module: []
clab:
  kind: linux
  config_templates:
  - hosts:/etc/hosts
  binds:
  - clab_files/h1/hosts:/etc/hosts
box: python:3.9-alpine
role: host
mtu: 1500
af:
  ipv4: true
mgmt:
  ifname: eth0
  ipv4: 192.168.121.104
  mac: 08:4f:a9:00:00:04
hostname: clab-netlab-h1
